import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
const fixture=vi.hoisted(()=>({status:'active',locked:false,events:[] as any[],goal:null as any,runGoal:vi.fn()}));
vi.mock('../goals/service.js',()=>({ChapterGoalService:class {get(){return fixture.goal;}events(){return {events:fixture.events};}run(...args:any[]){return fixture.runGoal(...args);}close(){}}}));
vi.mock('../state/manager.js',()=>({StateManager:class {async loadBookConfig(){return {status:fixture.status};}async acquireBookLock(){if(fixture.locked)throw new Error('busy');fixture.locked=true;return async()=>{fixture.locked=false;};}}}));
vi.mock('../harness/work-store.js',()=>({loadWorkManifest:async()=>({profileId:'longform-novel'})}));
vi.mock('../harness/builtin-profiles.js',()=>({createBuiltInWorkProfileRegistry:()=>({require:()=>({})})}));
vi.mock('../skills/index.js',()=>({loadAvailableAgentSkills:async()=>({skills:[]}),resolveProfileSkillActivations:()=>[]}));
import { AutonomousChapterRunner } from '../pipeline/autonomous-chapters.js';
import { SchedulerStore } from '../pipeline/scheduler-store.js';
const roots:string[]=[];const stores:SchedulerStore[]=[];
beforeEach(()=>{fixture.status='active';fixture.locked=false;fixture.events=[];fixture.goal=null;vi.clearAllMocks();});
afterEach(async()=>{stores.splice(0).forEach(s=>s.close());await Promise.all(roots.splice(0).map(p=>rm(p,{recursive:true,force:true})));});
async function setup(){const root=await mkdtemp(join(tmpdir(),'inkos-autonomous-'));roots.push(root);const store=new SchedulerStore(join(root,'harness.sqlite'));stores.push(store);const first=store.reserve('novel',4,Date.now(),1)!;const job={...first,phase:'reviewing' as const};store.save(job,'fixture');const pipeline={writeChapters:vi.fn(),runWithAbortSignal:(_s:any,f:any)=>f(),runWithAgentContext:(_c:any,f:any)=>f(),reviewChapter:vi.fn(async()=>({summary:'Current retained revision reviewed.',observations:[]})),reviseDraft:vi.fn()};const publisher={ready:vi.fn(async()=>{}),publish:vi.fn(async()=>({status:'published' as const,remoteChapterId:'remote-4'}))};let now=Date.now();const runner=new AutonomousChapterRunner(root,pipeline as any,store,{publisher,retryDelayMs:1,publicationPollMs:60000,now:()=>now});const revision=vi.spyOn(runner as any,'chapterRevision').mockResolvedValue({revisionId:'revision-4',observations:[]});return {root,store,job,pipeline,publisher,runner,revision,advance:()=>{now+=100000;}};}
const issue={code:'continuity',summary:'Unresolved source-supported issue',assessment:'issue',evidence:[]};
describe('autonomous retained chapter stages',()=>{
 it('publishes only the revision accepted under the existing book lock',async()=>{const f=await setup();f.revision.mockImplementation(async()=>{if(f.revision.mock.calls.length<=2)expect(fixture.locked).toBe(true);return {revisionId:'revision-4',observations:[]};});const result=await f.runner.run(f.job,new AbortController().signal);expect(result.phase).toBe('completed');expect(f.pipeline.reviewChapter).toHaveBeenCalledOnce();expect(result.reviewReceipt).toMatchObject({revisionId:'revision-4',summary:'Current retained revision reviewed.'});expect(f.publisher.publish).toHaveBeenCalledWith(expect.objectContaining({revisionId:'revision-4'}));expect(fixture.locked).toBe(false);});
 it('does not accept a changed revision with new unresolved observations',async()=>{const f=await setup();f.revision.mockResolvedValueOnce({revisionId:'A',observations:[]}).mockResolvedValue({revisionId:'B',observations:[{...issue,code:'state-sync-required'}]});const result=await f.runner.run(f.job,new AbortController().signal);expect(result.phase).toBe('blocked');expect(f.publisher.publish).not.toHaveBeenCalled();});
 it('retries an unavailable review without rewriting prose',async()=>{const f=await setup();f.revision.mockResolvedValueOnce({revisionId:'A',observations:[{code:'review-unavailable',summary:'provider timed out',evidence:[]}]}).mockResolvedValue({revisionId:'A',observations:[]});await f.runner.run(f.job,new AbortController().signal);expect(f.pipeline.reviewChapter).toHaveBeenCalledOnce();expect(f.pipeline.reviseDraft).not.toHaveBeenCalled();expect(f.publisher.publish).toHaveBeenCalledOnce();});
 it('performs at most one source-scoped repair and retains unresolved work',async()=>{const f=await setup();f.revision.mockResolvedValue({revisionId:'A',observations:[issue]});const result=await f.runner.run(f.job,new AbortController().signal);expect(result.phase).toBe('blocked');expect(f.pipeline.reviseDraft).toHaveBeenCalledWith('novel',4,'spot-fix',expect.any(String));expect(f.publisher.publish).not.toHaveBeenCalled();});
 it('retains a started repair across an exception instead of resetting the budget',async()=>{const f=await setup();f.revision.mockResolvedValue({revisionId:'A',observations:[issue]});f.pipeline.reviseDraft.mockRejectedValue(new Error('provider failed'));const first=await f.runner.run(f.job,new AbortController().signal);expect(first.reviewAttempts).toBe(1);expect(fixture.locked).toBe(false);f.advance();const second=await f.runner.run(first,new AbortController().signal);expect(second.phase).toBe('blocked');expect(f.pipeline.reviseDraft).toHaveBeenCalledOnce();});
 it('holds pending remote outcomes for later readback without a new writing call',async()=>{const f=await setup();f.publisher.publish.mockResolvedValue({status:'pending'} as any);const first=await f.runner.run(f.job,new AbortController().signal);expect(first.phase).toBe('publishing');expect(first.publication?.status).toBe('pending');expect(f.pipeline.writeChapters).not.toHaveBeenCalled();f.advance();await f.runner.run(first,new AbortController().signal);expect(f.publisher.publish).toHaveBeenCalledTimes(2);expect(f.pipeline.writeChapters).not.toHaveBeenCalled();});
 it('bounds unavailable transport retries and persists backoff',async()=>{const f=await setup();f.publisher.ready.mockRejectedValue(Object.assign(new Error('No configured browser'),{code:'PUBLISHING_UNAVAILABLE'}));let job=f.job as any;for(let i=0;i<3;i++){job=await f.runner.run(job,new AbortController().signal);f.advance();}expect(job.phase).toBe('blocked');expect(f.publisher.ready).toHaveBeenCalledTimes(3);await f.runner.run(job,new AbortController().signal);expect(f.publisher.ready).toHaveBeenCalledTimes(3);expect(f.pipeline.reviseDraft).not.toHaveBeenCalled();});
 it('respects an explicit pause before the first goal attempt',async()=>{const f=await setup();fixture.goal={id:f.job.goalId,status:'paused',desiredState:'paused',attempts:0,version:2,owner:null,budget:{expiresAt:Date.now()+60000}};fixture.events=[{type:'goal-created'},{type:'goal-paused-requested'}];const result=await f.runner.run({...f.job,phase:'writing'},new AbortController().signal);expect(result.phase).toBe('blocked');expect(fixture.runGoal).not.toHaveBeenCalled();expect(f.publisher.publish).not.toHaveBeenCalled();});
 it('does no new work for a paused book',async()=>{const f=await setup();fixture.status='paused';const result=await f.runner.run(f.job,new AbortController().signal);expect(result).toEqual(f.job);expect(f.publisher.ready).not.toHaveBeenCalled();});
 it('a failed completion callback cannot turn accepted output into another write',async()=>{const f=await setup();(f.runner as any).options.onComplete=()=>{throw new Error('notification failed');};const result=await f.runner.run(f.job,new AbortController().signal);expect(result.phase).toBe('completed');expect(f.publisher.publish).toHaveBeenCalledOnce();await f.runner.run(result,new AbortController().signal);expect(f.publisher.publish).toHaveBeenCalledOnce();expect(f.pipeline.writeChapters).not.toHaveBeenCalled();});

});


describe('revision-bound review and interrupted repair recovery',()=>{
 it('reviews an edited registered revision again even if metadata still has no issues',async()=>{const f=await setup();let current='A';f.revision.mockImplementation(async()=>({revisionId:current,observations:[]}));f.publisher.publish.mockResolvedValue({status:'pending'} as any);const accepted=await f.runner.run(f.job,new AbortController().signal);expect(accepted.reviewReceipt?.revisionId).toBe('A');current='B';f.advance();const invalidated=await f.runner.run(accepted,new AbortController().signal);expect(invalidated.phase).toBe('reviewing');expect(invalidated.reviewReceipt).toBeUndefined();expect(invalidated.reviewChecks).toBe(1);const reviewed=await f.runner.run(invalidated,new AbortController().signal);expect(reviewed.reviewReceipt?.revisionId).toBe('B');expect(reviewed.reviewChecks).toBe(2);expect(f.pipeline.reviewChapter).toHaveBeenCalledTimes(2);expect(f.publisher.publish).toHaveBeenLastCalledWith(expect.objectContaining({revisionId:'B'}));});
 it('does not publish a legacy phase without a durable current revision review receipt',async()=>{const f=await setup();const legacy={...f.job,phase:'publishing' as const,revisionId:'revision-4'};f.store.save(legacy,'legacy');const pending=await f.runner.run(legacy,new AbortController().signal);expect(pending.phase).toBe('reviewing');expect(f.publisher.publish).not.toHaveBeenCalled();const result=await f.runner.run(pending,new AbortController().signal);expect(result.reviewReceipt?.revisionId).toBe('revision-4');expect(f.pipeline.reviewChapter).toHaveBeenCalledOnce();});
 it('does not erase the audit budget through repeated edits',async()=>{const f=await setup();let current='A';f.revision.mockImplementation(async()=>({revisionId:current,observations:[]}));f.publisher.publish.mockResolvedValue({status:'pending'} as any);let job=await f.runner.run(f.job,new AbortController().signal);for(const next of ['B','C','D']){current=next;f.advance();job=await f.runner.run(job,new AbortController().signal);job=await f.runner.run(job,new AbortController().signal);}expect(job.phase).toBe('blocked');expect(job.error?.code).toBe('CHAPTER_REVIEW_BUDGET_EXHAUSTED');expect(f.pipeline.reviewChapter).toHaveBeenCalledTimes(3);expect(f.publisher.publish).toHaveBeenCalledTimes(3);});
 it('reconciles a repair committed just before stop and audits that revision without another repair',async()=>{const f=await setup(),controller=new AbortController();let current='A';f.revision.mockImplementation(async()=>({revisionId:current,observations:current==='A'?[issue]:[]}));f.pipeline.reviseDraft.mockImplementation(async()=>{current='B';controller.abort(new Error('ordinary daemon stop'));throw controller.signal.reason;});const stopped=await f.runner.run(f.job,controller.signal);expect(stopped.reviewAttempts).toBe(1);expect(stopped.reviewRepair?.revisionId).toBe('A');const restarted=new AutonomousChapterRunner(f.root,f.pipeline as any,f.store,{publisher:f.publisher,retryDelayMs:1});vi.spyOn(restarted as any,'chapterRevision').mockImplementation(async()=>({revisionId:current,observations:[]}));const result=await restarted.run(f.store.latest('novel')!,new AbortController().signal);expect(result.phase).toBe('completed');expect(result.reviewReceipt?.revisionId).toBe('B');expect(f.pipeline.reviseDraft).toHaveBeenCalledOnce();expect(f.pipeline.reviewChapter).toHaveBeenCalledTimes(2);});
 it('retains a stopped repair attempt and blocks when a fresh audit still finds the issue',async()=>{const f=await setup(),controller=new AbortController();f.revision.mockResolvedValue({revisionId:'A',observations:[issue]});f.pipeline.reviseDraft.mockImplementation(async()=>{controller.abort(new Error('ordinary stop'));throw controller.signal.reason;});const stopped=await f.runner.run(f.job,controller.signal);const resumed=await f.runner.run(stopped,new AbortController().signal);expect(resumed.phase).toBe('blocked');expect(resumed.reviewAttempts).toBe(1);expect(f.pipeline.reviseDraft).toHaveBeenCalledOnce();expect(f.pipeline.reviewChapter).toHaveBeenCalledTimes(2);expect(f.publisher.publish).not.toHaveBeenCalled();});
 it('will not reinterpret a canonical pending marker as an editorial repair',async()=>{const f=await setup();f.revision.mockResolvedValue({revisionId:'A',observations:[{code:'state-sync-required',summary:'Canonical state replay is pending.',evidence:[],assessment:'unavailable'}]});const result=await f.runner.run(f.job,new AbortController().signal);expect(result.phase).toBe('blocked');expect(result.error?.code).toBe('CHAPTER_STATE_RECOVERY_REQUIRED');expect(f.pipeline.reviewChapter).not.toHaveBeenCalled();expect(f.pipeline.reviseDraft).not.toHaveBeenCalled();expect(f.publisher.publish).not.toHaveBeenCalled();});
 it('rechecks newly added unresolved metadata before publishing an accepted revision',async()=>{const f=await setup();f.publisher.publish.mockResolvedValue({status:'pending'} as any);const accepted=await f.runner.run(f.job,new AbortController().signal);f.revision.mockResolvedValue({revisionId:'revision-4',observations:[issue]});f.advance();const result=await f.runner.run(accepted,new AbortController().signal);expect(result.phase).toBe('reviewing');expect(result.reviewReceipt).toBeUndefined();expect(f.publisher.publish).toHaveBeenCalledOnce();});
 it('retains audit attempts when the audit itself stops and bounds later read-only retries',async()=>{const f=await setup(),controller=new AbortController();f.pipeline.reviewChapter.mockImplementationOnce(async()=>{controller.abort(new Error('ordinary stop'));throw controller.signal.reason;});const stopped=await f.runner.run(f.job,controller.signal);expect(stopped.reviewChecks).toBe(1);expect(stopped.reviewAttempt?.revisionId).toBe('revision-4');const resumed=await f.runner.run(stopped,new AbortController().signal);expect(resumed.phase).toBe('completed');expect(resumed.reviewChecks).toBe(2);expect(resumed.reviewAttempt).toBeUndefined();expect(f.pipeline.reviewChapter).toHaveBeenCalledTimes(2);});
 it('passes the same current publishing chapter to readiness only for readback continuation',async()=>{const f=await setup();f.publisher.publish.mockResolvedValue({status:'pending'} as any);const accepted=await f.runner.run(f.job,new AbortController().signal);expect(f.publisher.ready.mock.calls[0]).toHaveLength(3);expect((f.publisher.ready.mock.calls[0] as any)[2]).toBeUndefined();f.advance();await f.runner.run(accepted,new AbortController().signal);expect(f.publisher.ready).toHaveBeenLastCalledWith('novel',expect.any(AbortSignal),4);});
});
