import {describe,it,expect,afterEach} from 'vitest';
import {RemoteWorkStore} from '../publishing/work-creation-store.js';
import {RemoteWorkCreationService, type RemoteWorkCreationPort} from '../publishing/work-creation-service.js';
import type {RemoteWorkInput, RemoteWorkRun, RemoteWorkBlocker} from '../publishing/work-creation-contracts.js';
const stores: RemoteWorkStore[]=[];
afterEach(()=>{for(const s of stores.splice(0))s.close();});
const input:RemoteWorkInput={workId:'new-work',destination:{provider:'fixture',platform:'meganovel',accountId:'account-1',accountLabel:'label',sessionId:'session-1'},
 metadata:{title:'Fixture story',blurb:'An original fixture for storage tests only.',genre:'fantasy',language:'en',aiAssisted:true}};
function fixture() {
 const store=new RemoteWorkStore(':memory:');stores.push(store);
 const events:string[]=[];let blocker:RemoteWorkBlocker|undefined;let found=true;
 const port:RemoteWorkCreationPort={withScope:async(_scope,_signal,fn)=>fn(),inspect:async data=>({destination:data.destination,blocker}),
  create:async run=>{expect(store.get(run.id).phase).toBe('create_unknown');events.push('create');return{remoteBookId:'fixture-book'};},
  observe:async(run:RemoteWorkRun)=>{events.push('observe');return found?{status:'found',receipt:{operationId:run.id,destination:run.input.destination,
   metadata:run.input.metadata,remoteBookId:'fixture-book',observedAt:Date.now(),evidence:'Simulated adapter independent readback',provenance:'independently_observed'}}:{status:'not_found'};}};
 return{store,port,events,service:new RemoteWorkCreationService(store,port),block:(v:RemoteWorkBlocker|undefined)=>blocker=v,found:(v:boolean)=>found=v};
}
describe('remote creation service (simulated port, no real platform)',()=>{
 it('unsupported adapter persists explicit status with zero attempts',async()=>{const f=fixture();const run=await new RemoteWorkCreationService(f.store).ensure(input,new AbortController().signal);expect(run.phase).toBe('ready');expect(run.attempts).toBe(0);expect(run.blocker?.status).toBe('unsupported');expect(f.events).toEqual([]);});
 it('create result is a hint; independent readback commits target and repeat is inert',async()=>{const f=fixture();const signal=new AbortController().signal;const run=await f.service.ensure(input,signal);expect(run.phase).toBe('bound');expect(run.targetId).toBeTruthy();expect(f.events).toEqual(['create','observe']);expect((await f.service.ensure(input,signal)).id).toBe(run.id);expect(f.events).toEqual(['create','observe']);});
 it('unknown/negative readback never authorizes a second creation after service restart',async()=>{const f=fixture();f.found(false);const signal=new AbortController().signal;const run=await f.service.ensure(input,signal);expect(run.phase).toBe('create_unknown');expect(run.blocker?.status).toBe('reconciliation_required');await new RemoteWorkCreationService(f.store,f.port).ensure(input,signal);expect(f.events).toEqual(['create','observe','observe']);f.found(true);expect((await f.service.ensure(input,signal)).phase).toBe('bound');expect(f.events.filter(x=>x==='create')).toHaveLength(1);});
 it('crash after unknown receipt and before create only reconciles, even if no book is found',async()=>{const f=fixture();const reserved=f.store.reserve(input);f.store.beginCreation(reserved.id,reserved.version);f.found(false);const run=await f.service.ensure(input,new AbortController().signal);expect(run.attempts).toBe(1);expect(f.events).toEqual(['observe']);});
 it('thrown create response still reconciles a remotely committed book',async()=>{const f=fixture();f.port.create=async()=>{f.events.push('create');throw new Error('network response lost');};const run=await f.service.ensure(input,new AbortController().signal);expect(run.phase).toBe('bound');expect(f.events).toEqual(['create','observe']);});
 it('required legal/identity confirmation does not create and resumes same zero-attempt operation',async()=>{const f=fixture();f.block({status:'needs_confirmation',code:'REMOTE_WORK_CONFIRMATION_REQUIRED',message:'Review the platform contract yourself.'});const signal=new AbortController().signal;const run=await f.service.ensure(input,signal);expect(run.attempts).toBe(0);expect(f.events).toEqual([]);f.block(undefined);expect((await f.service.ensure(input,signal)).id).toBe(run.id);expect(f.events).toEqual(['create','observe']);});
 it('wrong actual account cannot create or observe',async()=>{const f=fixture();f.port.inspect=async()=>({destination:{...input.destination,accountId:'different'}});const run=await f.service.ensure(input,new AbortController().signal);expect(run.blocker?.code).toBe('REMOTE_WORK_ACCOUNT_MISMATCH');expect(f.events).toEqual([]);});
 it('pause during inspection stops before create reservation',async()=>{const f=fixture();const run=await f.service.ensure(input,new AbortController().signal,()=>{throw new Error('paused');});expect(run.attempts).toBe(0);expect(f.events).toEqual([]);});
 it('abort after mutation retains uncertainty and resumes readback only',async()=>{const f=fixture();const controller=new AbortController();f.port.create=async()=>{f.events.push('create');controller.abort();throw new Error('interrupted');};const run=await f.service.ensure(input,controller.signal);expect(run.phase).toBe('create_unknown');expect(run.blocker?.status).toBe('reconciliation_required');expect((await f.service.ensure(input,new AbortController().signal)).phase).toBe('bound');expect(f.events).toEqual(['create','observe']);});
 it('foreign or merely asserted receipt cannot bind',async()=>{const f=fixture();f.port.observe=async run=>({status:'found',receipt:{operationId:run.id,destination:{...input.destination,accountId:'other'},metadata:input.metadata,remoteBookId:'fixture-book',observedAt:Date.now(),evidence:'wrong account',provenance:'independently_observed'}});const run=await f.service.ensure(input,new AbortController().signal);expect(run.phase).toBe('create_unknown');expect(run.receipt).toBeNull();expect(run.targetId).toBeNull();});
 it('concurrent calls cannot both commit creation admission',async()=>{const f=fixture();const signal=new AbortController().signal;await Promise.all([f.service.ensure(input,signal),new RemoteWorkCreationService(f.store,f.port).ensure(input,signal)]);expect(f.events.filter(x=>x==='create')).toHaveLength(1);expect(f.store.forWork(input.workId)?.phase).toBe('bound');});
});
