import { afterEach, describe, expect, it } from 'vitest';
import { mkdtemp, rm, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { SchedulerStore } from '../pipeline/scheduler-store.js';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import ts from 'typescript';
import { nextCronTime } from '../pipeline/schedule.js';
const roots:string[]=[]; const stores:SchedulerStore[]=[];
afterEach(async()=>{for(const store of stores.splice(0))store.close();await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})));});
async function setup(){const root=await mkdtemp(join(tmpdir(),'inkos-daemon-store-'));roots.push(root);const path=join(root,'harness.sqlite');const store=new SchedulerStore(path);stores.push(store);return {store,path};}
function close(store:SchedulerStore){store.close();stores.splice(stores.indexOf(store),1);}
describe('durable daemon ledger',()=>{
 it('keeps a reserved chapter and daily cap through close/reopen',async()=>{const {store,path}=await setup();const now=Date.parse('2026-10-06T12:00:00Z');const first=store.reserve('a',4,now,1)!;close(store);const reopened=new SchedulerStore(path);stores.push(reopened);expect(reopened.latest('a')).toEqual(first);expect(reopened.reserve('a',4,now,1)).toEqual(first);expect(reopened.reserve('b',1,now,1)).toBeUndefined();expect(reopened.reserve('b',1,now+86400000,1)?.chapter).toBe(1);});
 it('serializes daily allocation across independent connections',async()=>{const {store,path}=await setup();const other=new SchedulerStore(path);stores.push(other);expect(store.reserve('a',1,Date.now(),1)).toBeDefined();expect(other.reserve('b',1,Date.now(),1)).toBeUndefined();});
 it('charges carried-over writing against the new day without changing its goal',async()=>{const {store}=await setup();const yesterday=Date.parse('2026-10-05T23:59:00Z'),today=yesterday+120000;const job=store.reserve('a',4,yesterday,1)!;expect(store.admitWriting('a',4,today,1)).toBe(true);expect(store.latest('a')?.goalId).toBe(job.goalId);expect(store.reserve('b',1,today,1)).toBeUndefined();});
 it('holds one live daemon owner and releases only its own claim',async()=>{const {store,path}=await setup();const other=new SchedulerStore(path);stores.push(other);store.acquire();expect(()=>other.acquire()).toThrow('already owns');close(store);expect(()=>other.acquire()).not.toThrow();});
 it('recovers a crashed process owner and its reserved chapter without resetting quota',async()=>{const {store,path}=await setup();const modules=join(roots.at(-1)!,'compiled');await mkdir(join(modules,'pipeline'),{recursive:true});await mkdir(join(modules,'harness'));for(const part of ['pipeline/scheduler-store','harness/sqlite','harness/ownership-lock']){const source=await readFile(new URL(`../${part}.ts`,import.meta.url),'utf8');await writeFile(join(modules,part+'.js'),ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText);}const script=`const {SchedulerStore}=require(process.argv[1]);const s=new SchedulerStore(process.argv[2]);s.acquire();s.reserve('book',4,Date.now(),1);process.stdout.write('ready\\n');setInterval(()=>{},1000);`;const child=spawn(process.execPath,['-e',script,join(modules,'pipeline/scheduler-store.js'),path],{stdio:['ignore','pipe','pipe']});try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('child did not claim')),5000);child.stdout!.once('data',()=>{clearTimeout(timer);resolve();});child.once('error',reject);});expect(()=>store.acquire()).toThrow('already owns');const exit=once(child,'exit');child.kill('SIGKILL');await exit;expect(()=>store.acquire()).not.toThrow();expect(store.latest('book')?.chapter).toBe(4);expect(store.reserve('another',1,Date.now(),1)).toBeUndefined();}finally{if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');}},10000);
 it('directs stop to the current ledger owner and clears it for the next owner',async()=>{const {store,path}=await setup();store.acquire();const control=new SchedulerStore(path);stores.push(control);expect(control.requestStop()?.pid).toBe(process.pid);expect(store.stopRequested()).toBe(true);close(store);control.acquire();expect(control.stopRequested()).toBe(false);});
 it('retains next due time instead of restarting the interval',async()=>{const {store,path}=await setup();expect(store.nextAt('write',100)).toBe(100);store.schedule('write',900);close(store);const reopened=new SchedulerStore(path);stores.push(reopened);expect(reopened.nextAt('write',200)).toBe(900);});
 it('keeps pending readback and bounded backoff across restart',async()=>{const {store,path}=await setup();const first=store.reserve('a',1,1000,1)!;store.save({...first,phase:'publishing',nextAttemptAt:9000,publication:{status:'pending'}},'pending',2000);expect(store.hasPendingDue(8000)).toBe(false);close(store);const reopened=new SchedulerStore(path);stores.push(reopened);expect(reopened.hasPendingDue(9000)).toBe(true);expect(reopened.latest('a')?.publication?.status).toBe('pending');expect(reopened.events()[0]?.type).toBe('pending');});
});
describe('calendar cron scheduling',()=>{
 it('aligns 15 minute slots to UTC clock boundaries',()=>{expect(new Date(nextCronTime('*/15 * * * *',Date.parse('2026-10-06T12:07:31Z'))).toISOString()).toBe('2026-10-06T12:15:00.000Z');});
 it('honors day-of-week and fixed hour',()=>{expect(new Date(nextCronTime('0 2 * * 1',Date.parse('2026-10-06T03:00:00Z'))).toISOString()).toBe('2026-10-12T02:00:00.000Z');});
 it('accepts ranges, lists and Sunday 7',()=>{expect(new Date(nextCronTime('0,30 9-17 * * 7',Date.parse('2026-10-10T23:00:00Z'))).toISOString()).toBe('2026-10-11T09:00:00.000Z');});
 it.each(['*/0 * * * *','61 * * * *','0 25 * * *','nonsense','0 1 * * MON'])('rejects unsupported cron instead of silently running daily: %s',cron=>{expect(()=>nextCronTime(cron,Date.now())).toThrow();});
});
