import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mkdtemp, readFile, readdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
const fake=vi.hoisted(()=>({books:new Map<string,any>(),next:new Map<string,number>(),run:vi.fn(),radar:vi.fn(),init:vi.fn()}));
vi.mock('../pipeline/runner.js',()=>({PipelineRunner:class {runWithAbortSignal(_signal:any,fn:any){return fn();}runWithAgentContext(_ctx:any,fn:any){return fn();}runRadar(){return fake.radar();}initBook(...args:any[]){return fake.init(...args);}}}));
vi.mock('../state/manager.js',()=>({StateManager:class {bookDir(id:string){return id;}async isCompleteBookDirectory(){return true;}async listBooks(){return [...fake.books.keys()];}async loadBookConfig(id:string){return fake.books.get(id);}async getNextChapterNumber(id:string){return fake.next.get(id)??1;}}}));
vi.mock('../pipeline/autonomous-chapters.js',()=>({AutonomousChapterRunner:class {constructor(_root:any,_pipeline:any,readonly store:any){}run(job:any,signal:any){return fake.run(job,signal,this.store);}}}));
vi.mock('../harness/builtin-profiles.js',()=>({createBuiltInWorkProfileRegistry:()=>({require:()=>({})})}));
vi.mock('../skills/index.js',()=>({loadAvailableAgentSkills:async()=>({skills:[]}),resolveProfileSkillActivations:()=>[]}));
import { Scheduler } from '../pipeline/scheduler.js';
import { SchedulerStore } from '../pipeline/scheduler-store.js';
const roots:string[]=[];const schedulers:Scheduler[]=[];
beforeEach(()=>{fake.books.clear();fake.next.clear();vi.clearAllMocks();fake.radar.mockResolvedValue({recommendations:[],marketSummary:'observed',timestamp:new Date().toISOString()});fake.run.mockImplementation(async(job,signal,store)=>{signal.throwIfAborted();fake.next.set(job.workId,job.chapter+1);const result={...job,phase:'completed'};store.save(result,'fixture-committed');return result;});});
afterEach(async()=>{await Promise.all(schedulers.splice(0).map(s=>s.stop()));vi.useRealTimers();await Promise.all(roots.splice(0).map(r=>rm(r,{recursive:true,force:true})));});
async function setup(extra:any={}){const root=await mkdtemp(join(tmpdir(),'inkos-scheduler-'));roots.push(root);const config={projectRoot:root,client:{} as any,model:'fixture',radarCron:'0 */6 * * *',writeCron:'*/15 * * * *',maxConcurrentBooks:2,chaptersPerCycle:1,retryDelayMs:1000,cooldownAfterChapterMs:0,maxChaptersPerDay:1,...extra};const scheduler=new Scheduler(config);schedulers.push(scheduler);return {root,config,scheduler};}
function book(id:string,status='active'){fake.books.set(id,{id,status,targetChapters:20});}
async function idle(){for(let n=0;n<30;n++)await new Promise(resolve=>setImmediate(resolve));}
describe('scheduler calendar and lifecycle',()=>{
 it('reserves one daily slot across two concurrent books',async()=>{book('a');book('b');const {scheduler}=await setup();await scheduler.start();await idle();expect(fake.run).toHaveBeenCalledTimes(1);});
 it('does not restart the daily allowance or next interval',async()=>{book('a');const {scheduler,config}=await setup();await scheduler.start();await idle();await scheduler.stop();const next=new Scheduler(config);schedulers.push(next);await next.start();await idle();expect(fake.run).toHaveBeenCalledTimes(1);});
 it('resumes a retained publication job without admitting another chapter',async()=>{book('a');const {root,scheduler}=await setup();const store=new SchedulerStore(join(root,'.inkos/harness.sqlite'));const job=store.reserve('a',1,Date.now(),1)!;store.save({...job,phase:'publishing'},'pending');store.schedule('write',Date.now()+3600000);store.close();await scheduler.start();await idle();expect(fake.run).toHaveBeenCalledTimes(1);expect(fake.run.mock.calls[0][0].phase).toBe('publishing');});
 it('skips paused works and honors the selected work list',async()=>{book('old-a','paused');book('old-b','paused');book('new');book('other');const {scheduler}=await setup({workIds:['old-a','old-b','new']});await scheduler.start();await idle();expect(fake.run.mock.calls.map(c=>c[0].workId)).toEqual(['new']);});
 it('never lets a completed auto-created foundation bypass the explicit work list',async()=>{book('new');book('previous-auto');const {root,scheduler}=await setup({workIds:['new'],maxChaptersPerDay:3});const store=new SchedulerStore(join(root,'.inkos/harness.sqlite'));store.reserveFoundation({scanId:'old-scan',concept:'Old automatic concept',book:{id:'previous-auto'} as any,instruction:'fixture',phase:'completed',attempts:1,nextAttemptAt:0});store.close();await scheduler.start();await idle();expect(fake.run.mock.calls.map(c=>c[0].workId)).toEqual(['new']);});
 it('keeps pending foundation creation paused while fixed publication bindings are enabled',async()=>{const {root,scheduler}=await setup({publisher:{ready:vi.fn(),publish:vi.fn()},market:{platform:'meganovel',language:'en',maxSourceAgeMs:86400000,autoCreate:{maxActiveBooks:1,targetChapters:24,chapterWordCount:2000}}});const store=new SchedulerStore(join(root,'.inkos/harness.sqlite'));store.reserveFoundation({scanId:'old-scan',concept:'Old pending concept',book:{id:'previous-auto'} as any,instruction:'fixture',phase:'pending',attempts:0,nextAttemptAt:0});store.close();await scheduler.start();await idle();await (scheduler as any).radarScanInFlight;expect(fake.init).not.toHaveBeenCalled();const read=new SchedulerStore(join(root,'.inkos/harness.sqlite'));expect(read.foundations()[0].attempts).toBe(0);expect(read.events().some(event=>event.type==='market-selection-blocked')).toBe(true);read.close();});
 it('rechecks pause between chapters',async()=>{book('a');const base=fake.run.getMockImplementation()!;fake.run.mockImplementation(async(...args)=>{const result=await base(...args);fake.books.get('a').status='paused';return result;});const {scheduler}=await setup({chaptersPerCycle:2,maxChaptersPerDay:5});await scheduler.start();await idle();expect(fake.run).toHaveBeenCalledTimes(1);});
 it('stop aborts and drains the first operation without scheduling a late writer',async()=>{book('a');let finish!:()=>void;fake.run.mockImplementation(async(job,signal)=>{await new Promise<void>(resolve=>{finish=resolve;signal.addEventListener('abort',resolve,{once:true});});return job;});const {scheduler}=await setup();await scheduler.start();await idle();expect(fake.run).toHaveBeenCalledTimes(1);await scheduler.stop();finish();await idle();expect(scheduler.isRunning).toBe(false);expect(fake.run).toHaveBeenCalledTimes(1);});
 it('callback errors are contained and do not reject startup',async()=>{book('a');fake.run.mockRejectedValue(new Error('fixture-operation'));const {scheduler}=await setup({onError:()=>{throw new Error('notification');}});await expect(scheduler.start()).resolves.toBeUndefined();await idle();await expect(scheduler.stop()).resolves.toBeUndefined();});
 it('saves actual returned radar data for later selection',async()=>{const {root,scheduler}=await setup();await scheduler.start();await idle();await (scheduler as any).radarScanInFlight;const files=await readdir(join(root,'radar'));expect(files).toHaveLength(1);expect(JSON.parse(await readFile(join(root,'radar',files[0]),'utf8')).marketSummary).toBe('observed');});
 it('rejects a second live scheduler even when the PID file is absent',async()=>{const {scheduler,config}=await setup();await scheduler.start();const other=new Scheduler(config);schedulers.push(other);await expect(other.start()).rejects.toMatchObject({code:'DAEMON_BUSY'});});
 it('creates one original target-language foundation from a saved supported scan',async()=>{const now=new Date().toISOString();fake.radar.mockResolvedValue({scanId:'supported-scan',timestamp:now,marketSummary:'observed',evidence:[{id:'e1',platform:'meganovel',language:'en',title:'Existing benchmark',sourceUrl:'https://www.meganovel.com/rankings',fetchedAt:now}],recommendations:[{platform:'meganovel',language:'en',title:'A New Original',genre:'fantasy',concept:'A clock repairer bargains for time.',reasoning:'Observed audience',benchmarkTitles:['Existing benchmark'],evidenceIds:['e1']}]});fake.init.mockImplementation(async b=>{fake.books.set(b.id,b);});const {scheduler,root}=await setup({market:{platform:'meganovel',language:'en',maxSourceAgeMs:86400000,autoCreate:{maxActiveBooks:1,targetChapters:24,chapterWordCount:2000}}});await scheduler.start();await idle();await (scheduler as any).radarScanInFlight;expect(fake.init).toHaveBeenCalledOnce();expect(fake.init.mock.calls[0][0]).toMatchObject({language:'en',platform:'meganovel',title:'A New Original',targetChapters:24,chapterWordCount:2000});const store=new SchedulerStore(join(root,'.inkos/harness.sqlite'));expect(store.foundations()[0].phase).toBe('completed');store.close();});
 it('does not create a book from unsupported or unrelated recommendations',async()=>{fake.radar.mockResolvedValue({timestamp:new Date().toISOString(),marketSummary:'unsupported',recommendations:[{platform:'qidian',title:'Not English evidence',genre:'fantasy',concept:'x',reasoning:'x',benchmarkTitles:[]}]});const {scheduler}=await setup({market:{platform:'meganovel',language:'en',maxSourceAgeMs:86400000,autoCreate:{maxActiveBooks:1,targetChapters:24,chapterWordCount:2000}}});await scheduler.start();await idle();await (scheduler as any).radarScanInFlight;expect(fake.init).not.toHaveBeenCalled();});
 it('a ledger stop cancels admission before the next tick and releases the owner',async()=>{book('a');const {root,scheduler}=await setup();await scheduler.start();await idle();const store=new SchedulerStore(join(root,'.inkos/harness.sqlite'));store.requestStop();(scheduler as any).tick();await scheduler.stop();expect(scheduler.isRunning).toBe(false);expect(store.runningOwner()).toBeUndefined();store.close();});

});
